### ISSUE TITLE
Error: Expected messages to be array, provided: object

### ISSUE THREAD

**Issue by TeroFrondelius** [TeroFrondelius/linter-julia#1]
Probably a rookie mistake, but somewhere my Array is changed to Object, which doesn't have forEach method. I have made an extra forEach loop [here](https://github.com/TeroFrondelius/linter-julia/blob/7e46f35d778f67ce60c4b4199550887763f6fe61/lib/linter-julia.coffee#L78-L79) to test that the Array is correct before leaving the lint method. 

Here is the Atom console output:
![image](https://cloud.githubusercontent.com/assets/12501534/22519974/32189700-e8bb-11e6-8a98-2324d97cb5ab.png)

@steelbrain you were such a huge help earlier, could you give a quick look and help the rookie.

**Comment by steelbrain** [comment]
@TeroFrondelius while the code looks like it should work at first sight, a little bit looking around and you understand that the last line of the compile coffeescript would look like
```js
lint()
...
return connection.on('data', function(...) {
  ...
  return rout
})
```

The return value of `EventEmitter.on(...)` is `EventEmitter` itself so the error is very valid and is a classic case of asynchrony in javascript. You can use promises for fix this like

```js
lint(...):
return new Promise(function(resolve, reject) {
  data = []
  connection.on('error', reject)
  connection.on('data', function(chunk) { data.push(chunk) })
  connection.on('close', function() {
    const allOfData = data.join('')
    resolve(doSomeMagic(allOfData))
  })
})
```

**Comment by TeroFrondelius** [comment]
Apparently Lint.jl lintserver() doesn't send proper close signal or another my own rookie mistake. However, I found a [workaround](https://github.com/TeroFrondelius/linter-julia/blob/2d0dcda42e98f87e5990a20db5e1913820ac0331/lib/linter-julia.coffee#L80-L81) for this initial version to be used.

**Comment by TeroFrondelius** [comment]
@steelbrain big thanks for your help. I have a feeling I learned something.
