### ISSUE TITLE
disable suggestions while writing a string

### ISSUE THREAD

**Issue by CarloLucibello** [TeroFrondelius/linter-julia#21]
I just started using this package in Atom (btw nice work, it was a much needed one).
The linter keeps suggesting on while I'm writing a string:
![sel](https://cloud.githubusercontent.com/assets/7014210/23093345/c6d8d5c6-f5e0-11e6-89ea-61ac1afa5347.png)
Is it feasible to turn it off? Maybe this a Lint.jl issue

Bye,
Carlo

**Comment by TeroFrondelius** [comment]
@CarloLucibello I thought it's Juno feature. Can you confirm that the behavior ends when you disable linter-julia? You can also change these configurations from linter: https://github.com/steelbrain/linter/blob/v1/docs/guides/configuration.md

**Comment by CarloLucibello** [comment]
you are right, it's a juno "feature", thanks and sorry for the noise
