### ISSUE TITLE
Add `linter` package as dependency

### ISSUE THREAD

**Issue by dpsanders** [TeroFrondelius/linter-julia#25]

**Comment by TeroFrondelius** [comment]
This is done: https://github.com/TeroFrondelius/linter-julia/commit/4bfe6a7a8a79d19db58dbd2e038665c490032f3a

**Comment by TeroFrondelius** [comment]
Hi @steelbrain,
Can you help me on how to add linter dependency? 
```js
  "dependencies": {
    "atom-linter": "^8.0.0",
    "atom-package-deps": "^4.0.1",
    "linter": ">=1.11.0 <2.0.0"
  },
```
Current installation issue, because of above: https://github.com/TeroFrondelius/linter-julia/issues/27

**Comment by steelbrain** [comment]
Hi @TeroFrondelius to add linter as a dependency in your package, you have to use [`atom-package-deps`](https://github.com/steelbrain/package-deps#how-it-works). You can see it in action in [`linter-xo`](https://github.com/sindresorhus/atom-linter-xo/blob/77dce8fd0074234132060fee3c0701c3564d7d90/package.json#L52-L54) and others

**Comment by TeroFrondelius** [comment]
Thanks again @steelbrain
