### ISSUE TITLE
Hide linter warnings by clicking on icon

### ISSUE THREAD

**Issue by dpsanders** [TeroFrondelius/linter-julia#26]
It would be useful to be able to hide and show the linter warnings at the bottom of the Atom pane by clicking on a toolbar or icon.

**Comment by TeroFrondelius** [comment]
Check here: https://github.com/steelbrain/linter/blob/v1/docs/guides/configuration.md
`showErrorPanel`: Show a list of errors at the bottom of the editor, I think you can make a keyboard shortcut to switch on / off the list at the bottom. Like Ctrl + Shift + I is toggling the console. Anyway this is a linter feature and the right place for this issue would be there.

**Comment by dpsanders** [comment]
Submitted: https://github.com/steelbrain/linter/issues/1324

**Comment by dpsanders** [comment]
This is implemented in v2 of `linter`, but apparently `linter-julia` excludes that version?

**Comment by TeroFrondelius** [comment]
See here https://discuss.atom.io/t/help-on-linter-standard-linter-v2-example/38528
Is the linter v2 released yet? My plan is to start supporting the v2 after it is released.

**Comment by dpsanders** [comment]
Seems not...
