### ISSUE TITLE
Doesn't find julia for $PATH

### ISSUE THREAD

**Issue by specter119** [TeroFrondelius/linter-julia#32]
It seems that the linter-julia does not find `julia` from `$PATH`. I doesn't use `Juno` so I can't get the path of julia automatically.

**Comment by TeroFrondelius** [comment]
Hi @specter119 
How do you start julia normally? If you will open command prompt and type `julia` will julia start? In Atom press Ctrl + , (settings) go linter-julia and set-up the julia command to point your julia.exe.

**Comment by specter119** [comment]
Thanks @TeroFrondelius 

I usually type `julia` in  Iterm2, sorry to forgot to tell you I am using Mac. 

```
# which julia
/Users/Home/opt/bin/julia
```

It will work when I set up the julia command in linter-julia. But Atom will warn me if I leave the path with blank and `julia` is not located in `/usr/local/bin`, which is the default path of julia installed by homebrew-cask

**Comment by TeroFrondelius** [comment]
Good if you got it working. I need to update the documentation.
