### ISSUE TITLE
Julia not spawned despite being on the path in OSX

### ISSUE THREAD

**Issue by Ward9250** [TeroFrondelius/linter-julia#33]
On OSX, after installing Lint, checking out the latest version, and then installing linter-julia, starting up Atom results in it showing the developer pane, and showing an error message: Uncaught Error: spawn julia ENOENT in events.js:160. A notification says 'julia' could not be spawned. Is it installed and on your path? If so open an issue. My path is: 

```
N82106:~ bward$ echo $PATH
/Users/bward/.nvm/versions/node/v6.9.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/munki:/Library/TeX/texbin:/Users/bward/.rvm/bin:/Users/bward/github/julia/usr/bin
```

Julia's bin directory is the last entry on the path.

**Comment by TeroFrondelius** [comment]
Can you wait couple of minutes? Then you should see lintserver running port/pipe ... at the console, which opened. 

This is because Lint.jl is precompiling itself at the first time of use. Then press Ctrl + Shift + F5 to restart Atom, if this won't help shutdown Atom and start again. If either of these above won't work, please report back then it's a new bug.

**Comment by TeroFrondelius** [comment]
Also if you don't have Juno go to the linter-julia settings and write julia instead of get_from_juno (or something similar).

**Comment by Ward9250** [comment]
I've left it for some time and nothing new appears on the console. I do have juno, but the settings for linter-julia is set to 'julia', and the juno settings also use just 'julia'. The Juno functionality and julia console work.

**Comment by TeroFrondelius** [comment]
![image](https://cloud.githubusercontent.com/assets/12501534/23622455/69070642-02a7-11e7-9414-09f3d268d631.png)

try to write: `/Users/bward/github/julia/usr/bin/julia` to Julia executable location. Then you will need to restart by Ctrl + Shift + F5

**Comment by Ward9250** [comment]
Setting the exact location of the julia executable works, thanks!
