### ISSUE TITLE
linter-julia dosen't work on win10

### ISSUE THREAD

**Issue by AStupidBear** [TeroFrondelius/linter-julia#37]
![2017-03-12_210127](https://cloud.githubusercontent.com/assets/16422976/23832454/53a56074-076f-11e7-8d70-25bb42a74e0e.jpg)

**Comment by TeroFrondelius** [comment]
Did you follow installation instructions? Namely have you typed `Pkg.checkout ("Lint")`?

**Comment by AStupidBear** [comment]
Sorry for the bothering.
