### ISSUE TITLE
Follow the lintserver() message development towards JSON

### ISSUE THREAD

**Issue by TeroFrondelius** [TeroFrondelius/linter-julia#4]
See the discussion: https://github.com/tonyhffong/Lint.jl/issues/131

**Comment by TeroFrondelius** [comment]
Hi @steelbrain,
Sorry to ping you again, but I probably have another rookie mistake with async programming. Can you check if it is something obvious: https://github.com/TeroFrondelius/linter-julia/blob/JSON/lib/linter-julia.coffee

This version should be simpler than the original.

**Comment by steelbrain** [comment]
It looks fine, what's the current output and how do you think it is not the expected one? This information would help me narrow down the scan surface for the error

**Comment by TeroFrondelius** [comment]
Error:
`Uncaught SyntaxError: Unexpected end of JSON input`

I think I made the mistake on the julia side: https://github.com/tonyhffong/Lint.jl/pull/194
I will try to go back in time and make a diff what changed and is causing the problem. I really should add specs to this package.

**Comment by steelbrain** [comment]
Can you try a
```
console.log(JSON.parse(data.join('')))
```
before
```
resolve(JSON.parse(data.join('')))
```
and see if there are any syntax errors or extra spaces in the data

**Comment by TeroFrondelius** [comment]
This is the comparison to working version and current, changes in Lint.jl:
https://github.com/TeroFrondelius/Lint.jl/compare/1ccc0e9353817de6b1e4173e72b55df195a82882...TeroFrondelius:JSON

and in linter-julia: https://github.com/TeroFrondelius/linter-julia/compare/db8daf9...JSON

**Comment by TeroFrondelius** [comment]
I made some debug code outside Atom:
```coffee
net = require 'net'
Promise = require('promise')

str = """
     test = "Hello" + "World"
     nhalkjl
     """

port = "/tmp/testttt"
for i in [1..70]
  connection = net.createConnection(port)

  new Promise (resolve, reject) ->
    data = []
    connection.on 'connect', () ->
      #console.log "Opened connection to #{port}."
      inps = {
        'file': "str",
        'code_str': str
      }
      connection.write JSON.stringify(inps)
    connection.on('error',reject)
    connection.on 'data', (chunk) ->
      data.push(chunk)
    connection.on 'close', () ->
      resolve(console.log(JSON.parse(data.join(''))))
```
First run `i in [1..60]` and second `i in [1..70]`:
```bash
$ coffee testJSONbothways.coffee 
[ { filePath: 'str',
    range: [ [Object], [Object] ],
    text: 'E422 : string uses * to concatenate',
    type: 'error' },
  { filePath: 'str',
    range: [ [Object], [Object] ],
    text: 'E321 nhalkjl: use of undeclared symbol',
    type: 'error' } ]

 $ coffee testJSONbothways.coffee 

undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Socket.<anonymous> (/home/tero/dev/julialint/testJSONbothways.coffee:30:41)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
 $ 
```

**Comment by TeroFrondelius** [comment]
I think I found my bug: https://github.com/TeroFrondelius/Lint.jl/compare/a81d069...TeroFrondelius:ddefddb
```julia
if haskey(dict_data,"show_code")
    if !dict_data["show_code"]
        msgtext = "$evar: $txt"
    end
else
    msgtext = "$code $evar: $txt"
end
```
The bug is the case when `"show_code" = true`

**Comment by TeroFrondelius** [comment]
Implementation: f88b02a674b28dfaa92c7c352440ea6becd2335d
