### ISSUE TITLE
Use the indent as column_number 

### ISSUE THREAD

**Issue by TeroFrondelius** [TeroFrondelius/linter-julia#6]
![image](https://cloud.githubusercontent.com/assets/12501534/22552914/82246dde-e963-11e6-8fe6-f6774ee294d8.png)

This way the error message would show up where the text starts.

**Comment by TeroFrondelius** [comment]
I started also a conversation if Lint.jl could provide the error's columns https://github.com/tonyhffong/Lint.jl/issues/177, after all it could be more interesting to implement in Julia.

**Comment by TotalVerb** [comment]
Thanks for reporting these issues and helping to make Lint better. This is, as far as I can tell, a very big undertaking. It will need Lint to be able to understand source, not just ASTs. It's a desirable feature but there is some infrastructure that needs to be done first.

We first need a concrete syntax tree representation of syntax that does not throw away semantically meaningless but syntactically meaningful things like whitespace.

**Comment by TeroFrondelius** [comment]
Using the whole line width (80) works pretty ok. This is easy to add later, if Lint.jl or some other implementation will provide the column information.
