### ISSUE TITLE
Getting the server to internally launch

### ISSUE THREAD

**Issue by TeroFrondelius** [TeroFrondelius/linter-julia#8]
@HarrisonGrodin proposed here: https://github.com/JuliaEditorSupport/atom-language-julia/issues/8#issuecomment-277597255, that the server should be launched automatically.

**Comment by TeroFrondelius** [comment]
https://github.com/TeroFrondelius/linter-julia/pull/9

**Comment by grodinh** [comment]
@TeroFrondelius For some reason, although `ps agx | grep julia` shows the linter running, Atom does not show any real lint output. Interestingly, when I force-kill the linter process, it highlights lint errors.

**Comment by HarrisonGrodin** [comment]
@TeroFrondelius For some reason, although `ps agx | grep julia` shows the linter running, Atom does not show any real lint output. Interestingly, when I force-kill the linter process, it highlights lint errors.

**Comment by TeroFrondelius** [comment]
Sorry, I forgot to update the instructions in [README](https://github.com/TeroFrondelius/linter-julia/blob/master/README.md). I had to update the lintserver to close the connection correctly. See here if you are interested: https://github.com/tonyhffong/Lint.jl/commit/f1db4f054e8743099cea894af98c570062639812

So to get julia-linter working: `Pkg.checkout("Lint")` should do it. If this won't help, @HarrisonGrodin please open a new issue.
